# -*- coding: utf-8 -*-
"""Employees Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK8aWx9xOz2tZRqhXCOKqUbsnPGNG67W

# Connect to BigQuery
"""

# Libraries that we need
from google.cloud import bigquery
from google.colab import auth
import pandas as pd

# Authedicate
auth.authenticate_user()

# Initialize the client for BigQery
project_id = 'employees-churn-462815'
client = bigquery.Client(project=project_id, location='US')

# Get the datasets into table
dataset_ref = client.dataset('employeedata', project=project_id)
dataset = client.get_dataset(dataset_ref)
table_ref = dataset.table('hr_data')
table = client.get_table(table_ref)
new_table_ref = dataset.table('new_employees')
new_table = client.get_table(new_table_ref)

# Convert to dataframe
df = client.list_rows(table=table).to_dataframe()
df2 = client.list_rows(table=new_table).to_dataframe()

"""# Build Model

## Install Pycaret
"""

! pip install pycaret

"""# Code and Train Model"""

# Get our model
from pycaret.classification import *

df.info()

# Set up our model
setup(df,
      target='Quit_the_Company',
      session_id=123,
      ignore_features=['employee_id'],
      categorical_features=['salary', 'Departments'])

compare_models()

rf_model = create_model('rf')

final_df = predict_model(rf_model)

new_predictions = predict_model(rf_model, data=df2)

new_predictions.head()

#Write back to BigQuery
new_predictions.to_gbq('employeedata.pilot_predictions',
                       project_id,
                       chunksize=None,
                       if_exists='replace')

plot_model(rf_model, plot='feature')

# Create a feature table
feature_table = pd.DataFrame(zip(rf_model.feature_names_in_, rf_model.feature_importances_), columns=['feature','importance'])
feature_table

feature_table.to_gbq('employeedata.feature_table',
                     project_id,
                     chunksize=None,
                     if_exists='replace')

zip()